functional:
  - The user should be able to compete in writing code in different languages according to the given conditions for speed.
  - The user must be able to compete with another user or bot by creating a game.
  - The user should be able to invite a friend to join the game.
  - The user should be able to see the writing of the code by the enemy.
  - The user should be able to give up, reset the solution and check the solution.
  - The user should receive rating points after completing the game with another user or friend in case of victory.
  - The user should be able to view the rating of players for the week, month and all time.
  - The user should be able to choose the difficulty level of the game.
  - The user should be able to change the language of tasks from English to Russian and from Russian to English.
  - A user not participating in the game should be able to follow the progress of the game.
  - Users participating in the game and watching it should be able to send messages in the chat.
  - The user must be able to view the video recording of their games and games of other users.

non-functional:
  - The site should be designed with usability in mind and optimized for speed.
  - The site must be secure and protect user data.
  - The site should be convenient on a mobile device.
  - The site must be tested for compatibility with the latest versions of browsers.
  - The site must be able to handle a large amount of traffic (1000 concurrent users).

implicit:
  - To access the functionality of the site, the user must register or log in through Github or Discord.
  - The user should not be able to edit, copy and delete the opponent's code.
  - The user must be able to view the history of his games, as well as the games of other users of the site.
  - The user should be able to view the statistics of their wins, losses and capitulations.
  - The user should be able to change the profile settings, incl. name, programming language, sounds and volume.
  - The user must be able to link accounts on Github or Discord to the account, as well as untie them.
  - The user should be able to create championships and participate in them.
  - The user should be able to view the video recording of the championships.
  
   
