functional:
  - Пользователь должен иметь возможность соревноваться в написании кода на разных языках по заданным условиям на скорость.
  - Пользователь должен иметь возможность соревноваться с другим пользователем или ботом путем создания игры.
  - Пользователь должен иметь возможность приглашать друга присоединиться к игре по ссылке.
  - Пользователь должен иметь возможность видеть написание кода противником.
  - Пользователь должен иметь возможность сдаться, сбросить решение и проверить решение.
  - Пользователь должен получать очки рейтинга после завершения игры с другим пользователем или другом в случае победы.
  - Пользователь должен иметь возможность просматривать рейтинг игроков за неделю, месяц и все время.
  - Пользователь должен иметь возможность выбирать уровень сложности игры.
  - Пользователь должен иметь возможность менять язык заданий с английского на русский и с русского на английский.
  - Пользователь, не участвующий в игре, должен иметь возможность следить за ходом игры.
  - Пользователи, участвующие в игре и наблюдающие за ней, должны иметь возможность отправлять сообщения в чате.
  - Пользователь должен иметь возможность просматривать видео-запись своих игр и игр других пользователей.

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (1000 одновременных пользователей). 

implicit:
  - Для доступа к функционалу сайта пользователь должен зарегистрироваться или авторизоваться через Github или Discord.
  - Пользователь не должен иметь возможность редактировать код противника.
  - Пользователь должен иметь возможность просматривать историю своих игр, а также игр других пользователей сайта.
  - Пользователь должен иметь возможность просматривать статистику своих побед, проигрешей и капитуляций.
  - Пользователь должен иметь возможность менять настройки профиля, в т.ч. имя, язык программирования, звуки и громкость.
  - Пользователь должен иметь возможность привязывать к аккаунту аккаунты на Github или Discord, а также отвязывать их.
  - Пользователь должен иметь возможность создавать чемпионаты и участвовать в них.
  - Пользователь должен иметь возможность просматривать видео-запись чемпионатов.
  
   
